name: iska_quiz
description: Quiz appplication for ISKA 2019.

version: 1.0.0

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.0+9
  cloud_firestore: ^0.12.2
  firebase_storage: ^3.0.1
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  flutter_spinkit: ^3.1.0
  uuid: ^2.0.1
  cached_network_image: ^0.8.0
  progress_button:
    git:
      url: https://github.com/mwgriffiths88/ProgressButton.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/is_logo.png
    - assets/img/bowser_icon.png
    - assets/img/luigi_icon.png
    - assets/img/mario_icon.png
    - assets/img/peach_icon.png
    - assets/img/toad_icon.png
    - assets/img/wario_icon.png
    - assets/img/yoshi_icon.png
